booksnob/main/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^critic/', include('critic.urls')),
    url(r'^', include('reader.urls')),
   
]

booksnob/reader/urls.py
"""main URL Configuration

"""
from django.conf.urls import include, url
from django.contrib import admin

from reader import views
from reader.views import get_author_filter
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
	
	url(r'^home/', views.HomeView.as_view()),
	url(r'^regist/', views.Regist.as_view(), name = 'regist'),
    url(r'^login/$',  views.Login.as_view()),
    url(r'^logout/$',  views.LogOut.as_view()),
   # url(r'^accounts/logout/$', logout),
	#url(r'^get_author/$', get_author_filter),
	url(r'^get_author/$', views.AuthorView.as_view(), name = 'get_author'),
	url(r'^get_author/(?P<pk>\d+)/$', views.GetAuthorView.as_view(), name= 'get_view'),
	url(r'^get_list/$', views.GetAuthorList.as_view(), name = 'get_list'),
	url(r'^get_save/$', views.GetAuthorSave.as_view(), name = 'get_save'),
	url(r'^avatar/$', views.Avatar.as_view(), name = 'avatar'),
	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booksnob/reader/models.py
from django.db import models
from reader.managers import AuthorManager
from django import forms
from django.contrib.auth.models import User

class Author(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email = models.EmailField()
	filter_author = AuthorManager()
	objects = models.Manager()

	def __unicode__(self):
		return '{0} {1} {2}'.format(self.first_name, self.last_name, self.email)

class Book(models.Model):
	author = models.ForeignKey(Author)
	name = models.CharField(max_length=100)
	
	def __unicode__(self):
		return '{0} - {1}'.format(self.author, self.name)

class Reader(models.Model):
	name = models.CharField(max_length = 100)
	book = models.ManyToManyField(Book)

	def __unicode__(self):
		return '{0} {1}'.format(self.name, self.book)

class Profile(models.Model):
	user = models.OneToOneField(User)
	avatar = models.ImageField(upload_to = '/static/')

	def __unicode__(self):
		return '{0} {1}'.format(self.user, self.avatar)

booksnob/critic/forms.py
from django import forms
from reader.actions import get_books


class ReviewForm(forms.Form):
    book_name = forms.ChoiceField(choices=[
            (book,book) for book in get_books()
            ])
    #CHOICES = (('1','First'),('2','Second'))
    #book_name = forms.ChoiceField(choices =CHOICES)
    text = forms.CharField(widget=forms.Textarea)
        
        
    def send_email(self):
        # send email using the self.cleaned_data dictionary
        #print (self.cleaned_data)
        print('Book: {0}'.format(self.cleaned_data['book_name']))
        print('Messege: {0}'.format(self.cleaned_data['text']))
        


    

booksnob/reader/forms.py
from django import forms
from models import Author, Profile
from django.contrib.auth.forms import UserCreationForm

class AuthorForm(forms.ModelForm):
	class Meta:
		model = Author
		fields = '__all__'

class UserForm(UserCreationForm):

    class Meta:
        model = Profile
        fields = '__all__'

booksnob/reader/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, DetailView, ListView
from django.views.generic.edit import FormView, View
from reader.models import  Author, Book, Reader,Profile
from reader.actions import get_books,get_author,get_list
from forms import AuthorForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

from reader.forms import UserForm


class HomeView(TemplateView):
    template_name ='reader/home.html'
    #template_name ='testapp/home2.html'
    #template_name ='testapp/home3.html'
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        context['author_name'] = get_author()
            

        context['books'] = get_books()
        context['list'] = get_list()

        return context

def get_author_filter(request):
    #Author.filter_author.get_author()
    #if request.POST:
    form = AuthorForm()
    return HttpResponse(form)

class AuthorView(FormView):
    form_class = AuthorForm
    template_name = 'reader/author.html'
    success_url = '/critic/thanks'
    #def post(self, request,*args,**kwargs):
    def form_valid(self,form):
        self.object = form.save()
        print self.object
        return super(AuthorView, self).form_valid(form)

class GetAuthorView(DetailView):
    model = Author
    template_name = 'reader/author_view.html'

    # def get(self, request, *args, **kwargs):
        # print 1


class GetAuthorList(ListView):
    model = Author
    template_name = 'reader/author_view_list.html'
    
    def post(self,request,*args,**kwargs):
        q = request.POST.get('search','Bill')
        u = request.POST.get('up','')
              
        search = Author.objects.filter(first_name__icontains=q)
        if u =='up':
            search = search.order_by('id')
        else:
            search = search.order_by('-id')
        # up = Author.objects.filter(first_name__icontains=q).order_by('first_name')
        # down = Author.objects.filter(first_name__icontains=q).order_by('-first_name')
        #search = Author.objects.filter(first_name__istartswith=q)
        return render(request,self.template_name,
            {'author_list': search})


class GetAuthorSave(FormView):
    form_class = AuthorForm
    model = Author
    template_name = 'reader/save.html'
    success_url = '/get_save/'
    
    def form_valid(self,form):
        self.object = form.save()
        print self.object
        return super(GetAuthorSave, self).form_valid(form)


class Regist(FormView):
    form_class = UserCreationForm
    success_url = '/get_save/'
    template_name = 'reader/regist.html'

    def form_valid(self,form):
        self.object = form.save()
        return super(Regist, self).form_valid(form)

class Login(FormView):
    form_class = AuthenticationForm
    success_url = '/get_list/'
    template_name = 'reader/login.html'

    def form_valid(self,form):
        user = form.get_user()
        login(self.request,user)
        return super(Login, self).form_valid(form)


class LogOut(View):
    success_url = '/regist/'
    template_name = 'reader/base.html'

    def get(self,request):
        logout(request)
        return HttpResponseRedirect('/login')
'''    
@login_required
def EditProfile(request):
    user = request.user
    if request.method == "POST":
        usrform = UserForm(data=request.POST, instance=user)
        proform = ProfileForm(data=request.POST, instance=user.get_profile())
        if usrform.is_valid() and proform.is_valid():
            user = usrform.save()
            profile = proform.save(commit=False)
            profile.user = user
            profile.save()
            return HttpResponseRedirect('/avatar/')
        else:
            return render_to_response('/get_list/', {
                'profile': request.user.get_profile,
                'usrform': usrform,
                'proform': proform},
                context_instance=RequestContext(request))
    else:
        usrform = UserForm(instance=user)
        proform = ProfileForm(instance=user.get_profile() )
        profile = request.user.get_profile
        return render(request, "/get_list/", {
            'profile': profile,
            'usrform': usrform,
            'proform': proform,
            })
'''
#@login_required
class Avatar(FormView):

    def get(self, request):
        form = UserForm()
        return render(request, 'reader/avatar.html', {'form': form})

    def post(self, request):
        #username = request.POST['user']
       # password = request.POST['password']
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/critic/thanks/')
        return render(request, 'reader/avatar.html', {'form': form})

booksnob/reader/templates/reader/author.html
{% extends "reader/base.html" %}

{% block title %}Django !{% endblock %}

{% block content %}
    <hr>
    <div class="form-group col-xs-12">
        
        <form method='post' action={% url 'get_author' %}>{% csrf_token %}
            {{form.as_p}}
        <br>
        <button type="submit" class="btn btn-primary btn-lg active" value="Send"> Send</button>
        
    </div>
        </form>
        
      
{% endblock %}

booksnob/reader/templates/reader/author_view.html
{% extends 'reader/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}
    
    <h3>Information about author</h3>
    <form method='post' action={% url 'get_save' %}>{% csrf_token %}
    <div class="form-group">
    	<label for="first_name"> First name:</label><textarea id="id_text" name="first_name" rows=1 >{{author.first_name}}</textarea>

    </div>
    <div class="form-group">
		<label for="last_name" >Last name:</label> <textarea id="id_text" name="last_name" rows=1>{{author.last_name}}</textarea>
	</div>
	<div class="form-group">
		<label for="email">Email:</label> <textarea id="id_text" name="email" rows=1>{{author.email}}</textarea>
    </div>

    <button type="submit" class="btn btn-success" value="Save"> Save</button>
    </form>
    <br>
    <a href="{%url 'get_list' %}"><p>К списку авторов</p></a><br>  
{% endblock %}

booksnob/reader/templates/reader/author_view_list.html
{% extends 'reader/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}
    <div class="col-xs-12">
    	User: {{user.username}}
    	<h3>List of authors: </h3>
    	<form action='' method='post'>{% csrf_token %}
    	<input type="radio" name="up" value = up> Up<Br>
    	<input type="radio" name="up" value = down> Down<Br>
    	<label for="id_author">Search<input id="id_author" maxlength="40" name="search" type="text" /></label>

    	{% for o in author_list %}
			<a href="{%url 'get_view' o.pk%}"><p> {{o.pk}}: {{o.first_name}}</p></a><br>
		
		{% endfor %}
		<button type="submit" class="btn btn-primary btn-lg active" value="Send"> Send</button>
		<img src='/static/avatar.png'>
		</form>
    </div>
        
{% endblock %}

booksnob/reader/templates/reader/avatar.html
{% extends 'reader/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}

<div>
    <hr>
    <form method="POST" action={% url 'avatar' %} enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p}}
            <hr>
     <input type="submit" class='btn btn-primary' value="Save user" />

    
    </form>
    {% load staticfiles %}
    <img src="{% static 'avatar.jpg' %}" />

    <img src="{{ Profile.avatar.url }}" />
</div>
        
{% endblock %}

booksnob/reader/templates/reader/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body><form action='' method='post'>{% csrf_token %}

<a href='../logout'>Exit</a>
</form>
    <h1><center>Welcome to my site</center></h1>
<div  class="form-group col-xs-12 ">
	    {% if user.is_authenticated %}
   		Welcome, {{user.username}}
    {% else%}
   		Please, log in!  
    {% endif %}

</div>
    {% block content %}


    {% endblock %}
<hr>  
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> 

{% block footer %}
    
    <p><center>Thanks for visiting my site.</center></p>
{% endblock %}

</body>
</html>

booksnob/reader/templates/reader/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <title>Ok Django!</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    
  </head>
  <body>
  <h1>Authors</h1>
  Hi there!
  {{author_name}}<br><br>
  {{books}}
  <br><br><br>
  <div class="container-fluid">
    <div class="row">
       <div class="col-xs-4">
     <!--  {%for author in author_name %}
       	<p class="bg-primary">{{author}} </p>
        {% endfor %}
        </div>-->
        
     <div class="col-xs-12">
      	<ul class="list-group">
          <!--<li class="list-group-item">{{ book }} </li>-->
      	 {%for author in author_name %}
      			<li class="list-group-item">{{ author }} </li>
      		{% empty %}
      			<li> No books</li>
      		{% endfor %}
      	</ul>
        <ul class="list-group">
          <!--<li class="list-group-item">{{ book }} </li>-->
         
            <li class="list-group-item">{{ book }} </li>
          
            
        </ul>
      </div>
  
    </div>
  </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>

booksnob/reader/templates/reader/login.html
{% extends 'reader/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}


	<form role="form" action='' method='post'>{% csrf_token %}
  <div class="form-group col-xs-12 ">
    <label  for="username">Username:</label>{{form.username}}
</div>
    <div class="form-group col-xs-12 ">
    <label  for="pass">Password</label>{{form.password}}
  </div>
  <div class="form-group col-xs-12 ">
     <button type="submit" class="btn btn-default" value="Send"> Send</button>
  </div>
  
	</form>



 
<!--   <div class="container">

      <form class="form-signin" role="form" action='' method='post'>{% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="login" class="form-control" placeholder="Login" required autofocus>
        <input type="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div>-->

  

{% endblock %}

booksnob/reader/templates/reader/regist.html
{% extends 'reader/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}
<div class="form-group col-xs-12">
    <form action='' method='post'>{% csrf_token %}
    {{form.as_p}}

    <button type="submit" class="btn btn-primary btn-lg active" value="Send"> Send</button>
    </form> 
</div>   
{% endblock %}

booksnob/reader/templates/reader/save.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Saved!</title>
</head>
<body>
   
<h1><center>Successfully saved!!!</center></h1>
<hr>


</body>
</html>

booksnob/reader/templates/reader/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Thanks</title>
<!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<h1><p class="text-center">Thank you for choice!</p></h1>
<hr>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> 
</body>
</html>